apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      serviceAccountName: monitoring  
      initContainers:
      - name: init-container
        image: curlimages/curl:latest  
        command: ['sh', '-c', 'curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc.cluster.local/metrics -o /usr/share/nginx/html/metrics.html']  
        volumeMounts:
        - name: hw-volume
          mountPath: /usr/share/nginx/html
      containers:
      - name: web-server
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hw-volume
          mountPath: /usr/share/nginx/html  
      volumes:
      - name: hw-volume
        emptyDir: {}
      - name: kube-api-access
        projected:
          sources:
          - serviceAccountToken:
              path: token  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
