apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'mkdir -p /init/conf && echo "<h1>Hello, World!</h1>" > /init/conf/file.html']
        volumeMounts:
        - name: hw-volume
          mountPath: /init
      containers:
      - name: web-server
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hw-volume
          mountPath: /usr/share/nginx/html
        - name: config-volume
          mountPath: /homework/conf  
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "rm -f /homework/conf/index.html"]
        readinessProbe:
          httpGet:
            path: /conf/index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: hw-volume
        persistentVolumeClaim:
          claimName: hw-pvc
      - name: config-volume
        configMap:
          name: hw-config 
      nodeSelector:
        homework: "true"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
