apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      tolerations:
        - key: "node-role"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"
      nodeSelector:
        node-role: "infra"
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'echo "<h1>Hello, World!</h1>" > /init/index.html']
        volumeMounts:
        - name: hw-volume
          mountPath: /init
      containers:
      - name: web-server
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hw-volume
          mountPath: /usr/share/nginx/html
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "rm -f /usr/share/nginx/html/index.html"]
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: hw-volume
        emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
