apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw-ingress
  namespace: homework
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: homework.otus
    http:
      paths:
      - path: /homepage$
        pathType: ImplementationSpecific
        backend:
          service:
            name: hw-service
            port:
              number: 80        