apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networks
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: 'https://github.com/Kuber-2024-12OTUS/1uanv1_repo.git'
    targetRevision: 'kubernetes-networks'
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homework
  syncPolicy: {}
