apiVersion: v1
kind: Pod
metadata:
  name: s3-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c", "while true; do echo $(date) >> /mnt/data/log.txt; sleep 10; done"]
      volumeMounts:
        - mountPath: "/mnt/data"
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: csi-s3-pvc-dynamic
