apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-storage    
