apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-role
  namespace: default
rules:
  - apiGroups: ["otus.homework"]
    resources: ["mysqls"]
    verbs: ["create", "delete", "get", "list", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: ["v1"]
    resources: ["services", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["create", "delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: mysql-operator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: mysql-operator-role
  apiGroup: rbac.authorization.k8s.io

