apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
stringData:
  accessKey: YCAJE_Z6s66NcJPQGvcSKprK-
  secretKey: YCM4-r4xQ2oJnAfRM3gyj1SGapJyFNywxbqQk4he
  endpoint: https://storage.yandexcloud.net
