apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: kube-system
stringData:
  accessKeyID: YCAJE4FZqQ2WcIskzsCyCGf0W
  secretAccessKey: YCOI3MAAvhSf9CzRr2Xg31xvpsRbvHFsMIeLOzUS
  endpoint: https://storage.yandexcloud.net
