apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: templating
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: 'https://github.com/Kuber-2024-12OTUS/1uanv1_repo.git'
    path: 'hw-chart'
    targetRevision: 'kubernetes-templating'
  destination:
    server: https://kubernetes.default.svc
    namespace: homeworkhelm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
