ui:
  enabled: true

server:
  ha:
    enabled: true
    replicas: 3

    config: |
      storage "consul" {
        path = "vault"
        address = "consul-consul-server.consul:8500"
      }
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }  
