apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
          - path: /index.html
            pathType: Exact
            backend:
              service:
                name: hw-service
                port:
                  number: {{ .Values.servicePort }}

