apiVersion: v2
name: hw-chart
description: A Helm chart for Kubernetes
version: 0.1.0
dependencies:
  - name: mysql
    version: 1.6.9
    repository: https://charts.helm.sh/stable
    condition: dependencies.mysql.enabled
